### ISSUE TITLE
Epic: Add Java 17 language support

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9869]
This will be one of the leading features for GWT 2.12 - we've experimentally built out more than half of the new features already. The limiting factor is that in order to support a newer JDT, we will need to raising support for running Compiler/DevMode/CodeServer/JUnitShell to Java 11.

Subtasks:
- [x] #9870
- [ ] Optional: Explore CI testing for running server classes on Java 8. Will need additional resourcing/testing - this doesn't appear to be a priority for the vast majority of users. An alternative could be to backport fixes to release/2.11 as requested.
- [x] #9871
- [x] #9859
- [x] Add tests for Java 15 text blocks https://openjdk.org/jeps/378
- [x] Add tests for Java 17 sealed classes https://openjdk.org/jeps/409
- [x] #9894
- [x] #9893
- [x] #9878

JRE emulation changes, if any, should be filed in a different task. While reviewing JEPs, I only noticed https://openjdk.org/jeps/356, which may not apply anyway.

**Comment by jnehlmeier** [comment]
Shouldn't we try to aim 21 directly? Eclipse 2023-12 seems to support it so I guess some JDT should exist?

**Comment by niloc132** [comment]
@jnehlmeier 
For the JDT, if already stable, with support for all features, and still supports running on Java 11 I'd agree. Otherwise, I'd personally vote for incrementally building these features and using this issue as a milestone for Java 17, with a follow up milestone (likely for a later release?) for Java 21.

Besides the reasons above, we don't have a lot of PR reviewers anyway, I wouldn't want to say that we can't ship GWT 2.12 until all of 17 and 21 are finished.

**Comment by niloc132** [comment]
Looks like there are just two non-preview language JEPs in 18/19/20/21: https://openjdk.org/jeps/440 and https://openjdk.org/jeps/441. I haven't checked an updated JDT yet, but at least 441 looks like it will need codegen changes.

**Comment by niloc132** [comment]
Closing as completed.
